version: '3.7'

services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cookbook
    ports:
      - '3306:3306'
    expose:
      - 3306
  app:
    build: ./
    env_file: .env
    depends_on:
      - mysql
    ports:
      - '3000:3000'
